### ISSUE TITLE
Installing MoreLINQ NuGet 4.2 "Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))"

### ISSUE THREAD

**Issue by MeaningOfLights** [morelinq/MoreLINQ#1066]
UPDATE: Running VS2022 as Admin and installing does work, not for a user.

I try to install it via Nuget and it fails with the error:
![image](https://github.com/morelinq/MoreLINQ/assets/19789657/ffdf599d-f2da-465f-9e0c-221a0cbfca2e)

Specs:
Win 10
Dell Laptop Intel 13
Microsoft Visual Studio Professional 2022 (64-bit) - Preview Version 17.10.0 Preview 1.0
.Net 4.8 Framework in a Class Library Project

I haven't had issues installing other nugets. It could be an issue with VS2022.

Here's the Package Manager Output when I install:

System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at VSLangProj150.Reference6.get_SourceProject()
   at NuGet.PackageManagement.VisualStudio.VsManagedLanguagesProjectSystemServices.<GetProjectReferencesAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.<GetPackageSpecAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.<GetPackageSpecsAndAdditionalMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpecAndAdditionalMessages>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<PreviewRestoreProjectsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectsActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewProjectsInstallPackageAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass22_0.<<GetInstallActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__33`1.MoveNext()
Time Elapsed: 00:00:00.0419045

**Comment by atifaziz** [comment]
I am surprised you didn't have the same trouble with other packages. Perhaps they were already previously cached? Did you try with other NuGet clients.

> UPDATE: Running VS2022 as Admin and installing does work, not for a user.

Given this, I don't think this a problem specific to MoreLINQ's package. It seems linked to your environment and setup. You should [get help on repo for NuGet client issues](https://github.com/NuGet/Home). I'm going to close this unless we can definitely identify that the problem has to do with how the MoreLINQ package is built, if something can be done about it and it's in our control.
