### ISSUE TITLE
Missing null arg checks and tests

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#110]
Several methods are missing null arg checking and corresponding unit tests. This issue was created from larger efforts started by @yln as part of issue #94 and more specifically PR #109.

The work on this issue is currently taking place on the [null-checks](https://github.com/morelinq/MoreLINQ/tree/null-checks) branch that branches off v1.

At b7e623bec24bba7f9aa75b6876ca8828b12f7025, 227 tests were passing:

```
NUnit-Console version 2.6.2.12296
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8662 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
...................................................................................................................................................................................................................................
Tests run: 227, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0.8109916 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
```

As of b4bc5a7dd504c526642ef73afad828e9e64e36e1, 440 tests are passing (some of which may be duplicates to hand-written null check tests):

```
NUnit-Console version 2.6.2.12296
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8662 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
........................................................................................................................................................................................................................................................................................................................................................................................................................................................
Tests run: 440, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0.8280372 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
```

**Comment by atifaziz** [comment]
The fixes have been rolled into [v1 branch](https://github.com/morelinq/MoreLINQ/tree/v1) and released as [1.2](https://www.nuget.org/packages/morelinq/1.2.0), including the [portable version](https://www.nuget.org/packages/MoreLinq.Portable/1.2.0).

**Comment by atifaziz** [comment]
Pushed a new branch called [`v2-null-checks`][v2-null-checks] that has `null-checks` merged (see b99071c6e708a42d96cdee4c30058fef71da4ae6) and also ported over original changes from @yln. There are now 4 failing tests:

```
NUnit-Console version 2.6.2.12296
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 2.0.50727.5472 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
......................................................................................................................................................................................................................F.............................................................................................................................................................................F..........................................F..F...................................................................................................................................................................................................................................................................................................
Tests run: 722, Errors: 0, Failures: 4, Inconclusive: 0, Time: 5.1015101 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Failure : MoreLinq.Test.NullArgumentTest.ThenBy: 'comparer' (2);
System.Linq.IOrderedEnumerable`1[T] ThenBy[T,TKey](System.Linq.IOrderedEnumerable`1[T], System.Func`2[T,TKey], System.Collections.Generic.IComparer`1[TKey], MoreLinq.OrderByDirection)
     Expected: No Exception to be thrown
  But was:   (Object of type 'System.Int32[]' cannot be converted to type 'System.Linq.IOrderedEnumerable`1[System.Int32]'.)
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MoreLinq.Test.NullArgumentTest.TestCase.Invoke() in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 62
   at MoreLinq.Test.NullArgumentTest.<>c__DisplayClass4.<CanBeNull>b__3() in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 42
   at NUnit.Framework.Constraints.ThrowsNothingConstraint.Matches(Object actual)

at MoreLinq.Test.NullArgumentTest.CanBeNull(TestCase testCase) in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 42

2) Test Failure : MoreLinq.Test.NullArgumentTest.Assert: 'errorSelector' (2);
System.Collections.Generic.IEnumerable`1[TSource] Assert[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean], System.Func`2[TSource,System.Exception])
     Expected: <System.ArgumentNullException>
  But was:  null

at MoreLinq.Test.NullArgumentTest.NotNull(TestCase testCase) in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 35

3) Test Failure : MoreLinq.Test.NullArgumentTest.ThenBy: 'keySelector' (1);
System.Linq.IOrderedEnumerable`1[T] ThenBy[T,TKey](System.Linq.IOrderedEnumerable`1[T], System.Func`2[T,TKey], MoreLinq.OrderByDirection)
     Expected: <System.ArgumentNullException>
  But was:  <System.ArgumentException> (Object of type 'System.Int32[]' cannot be converted to type 'System.Linq.IOrderedEnumerable`1[System.Int32]'.)
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MoreLinq.Test.NullArgumentTest.TestCase.Invoke() in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 62
   at MoreLinq.Test.NullArgumentTest.<>c__DisplayClass1.<NotNull>b__0() in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 35
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)

at MoreLinq.Test.NullArgumentTest.NotNull(TestCase testCase) in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 35

4) Test Failure : MoreLinq.Test.NullArgumentTest.ThenBy: 'keySelector' (1);
System.Linq.IOrderedEnumerable`1[T] ThenBy[T,TKey](System.Linq.IOrderedEnumerable`1[T], System.Func`2[T,TKey], System.Collections.Generic.IComparer`1[TKey], MoreLinq.OrderByDirection)
     Expected: <System.ArgumentNullException>
  But was:  <System.ArgumentException> (Object of type 'System.Int32[]' cannot be converted to type 'System.Linq.IOrderedEnumerable`1[System.Int32]'.)
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MoreLinq.Test.NullArgumentTest.TestCase.Invoke() in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 62
   at MoreLinq.Test.NullArgumentTest.<>c__DisplayClass1.<NotNull>b__0() in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 35
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)

at MoreLinq.Test.NullArgumentTest.NotNull(TestCase testCase) in C:\MoreLINQ\MoreLinq.Test\NullArgumentTest.cs:line 35
```

@yln If we can fix these, then we're done for 2.0.

  [v2-null-checks]: https://github.com/morelinq/MoreLINQ/commits/v2-null-checks

**Comment by yln** [comment]
Okay, will do. Give me a few days.

**Comment by yln** [comment]
Will this be merged into master?

**Comment by atifaziz** [comment]
@yln [Merged into `master`](https://github.com/morelinq/MoreLINQ/commit/379ba62cb03263a6ef7baa31160960f0053467f6)

**Comment by yln** [comment]
2.x "stable" release and I am happy. ;)

**Comment by atifaziz** [comment]
Yes. :) I'd like to push it through the door now and while #118 just came in, I think it can go into 2.1 as it's something completely new. However, we do need to conclude on #116 as some bits in there are fine while others [debatable](https://github.com/morelinq/MoreLINQ/pull/116#issuecomment-144799743).
