### ISSUE TITLE
VS Test Explorer does not discover tests

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#362]
This is a follow-on issue from PR #361.

In spite of adding packages like `NUnit3TestAdapter`, Visual Studio is unable to run tests because they cannot be discovered (due to errors in Mono.Cecil?):

```
[22/11/2017 10:16:16 Informational] ------ Run test started ------
[22/11/2017 10:16:18 Informational] NUnit Adapter 3.9.0.0: Test execution started
[22/11/2017 10:16:18 Informational] Running all tests in A:\MoreLINQ\main\MoreLinq.Test\bin\Debug\netcoreapp1.0\MoreLinq.Test.dll
[22/11/2017 10:16:19 Warning] Exception System.NotImplementedException, Exception thrown executing tests in A:\MoreLINQ\main\MoreLinq.Test\bin\Debug\netcoreapp1.0\MoreLinq.Test.dll
[22/11/2017 10:16:19 Warning] GenericInst
[22/11/2017 10:16:19 Warning]    at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type)
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid)
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record)
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Cecil.MethodDefinition.get_DebugInformation()
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.FirstOrDefaultSequencePoint(MethodDefinition testMethod)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName)
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)
[22/11/2017 10:16:19 Informational] NUnit Adapter 3.9.0.0: Test execution complete
[22/11/2017 10:16:19 Warning] No test is available in A:\MoreLINQ\main\MoreLinq.Test\bin\Debug\netcoreapp1.0\MoreLinq.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[22/11/2017 10:16:19 Informational] ========== Run test finished: 0 run (0:00:03.4760332) ==========
[22/11/2017 10:32:21 Informational] ------ Discover test started ------
[22/11/2017 10:32:22 Informational] NUnit Adapter 3.9.0.0: Test discovery starting
[22/11/2017 10:32:25 Warning] Exception System.NotImplementedException, Exception converting MoreLinq.Test.IncrementalTests.TestNullSequenceException1
[22/11/2017 10:32:25 Warning] GenericInst
[22/11/2017 10:32:25 Warning]    at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type)
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid)
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record)
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Cecil.MethodDefinition.get_DebugInformation()
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.FirstOrDefaultSequencePoint(MethodDefinition testMethod)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName)
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.ProcessTestCases(XmlNode topNode, ITestCaseDiscoverySink discoverySink, TestConverter testConverter)
[22/11/2017 10:32:25 Warning] Exception System.NotImplementedException, Exception converting MoreLinq.Test.IncrementalTests.TestNullSequenceException2
[22/11/2017 10:32:25 Warning] GenericInst
[22/11/2017 10:32:25 Warning]    at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type)
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid)
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record)
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Cecil.MethodDefinition.get_DebugInformation()
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.FirstOrDefaultSequencePoint(MethodDefinition testMethod)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName)
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.ProcessTestCases(XmlNode topNode, ITestCaseDiscoverySink discoverySink, TestConverter testConverter)
[22/11/2017 10:32:26 Informational] NUnit Adapter 3.9.0.0: Test discovery complete
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.EndsWithTest.EndsWithWithChars(System.Char[],System.Char[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.EndsWithTest.EndsWithWithChars(System.Char[],System.Char[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.EndsWithTest.EndsWithWithIntegers(System.Int32[],System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.EndsWithTest.EndsWithWithIntegers(System.Int32[],System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.StartsWithTest.StartsWithWithChars(System.Char[],System.Char[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.StartsWithTest.StartsWithWithChars(System.Char[],System.Char[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.StartsWithTest.StartsWithWithIntegers(System.Int32[],System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.StartsWithTest.StartsWithWithIntegers(System.Int32[],System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(-1,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(-1,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(-1,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(-1,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(-1,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(-1,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(10,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(10,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(10,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(10,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(10,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Warning] A test with the same name 'MoreLinq.Test.ToArrayByIndexTest.ToArrayByIndex(10,System.Int32[])' already exists. This test is not added to the test window.
[22/11/2017 10:32:26 Informational] NUnit Adapter 3.9.0.0: Test discovery starting
[22/11/2017 10:32:26 Informational] Assembly contains no NUnit 3.0 tests: A:\MoreLINQ\main\MoreLinq\bin\Debug\net40\MoreLinq.dll
[22/11/2017 10:32:26 Informational] NUnit Adapter 3.9.0.0: Test discovery complete
[22/11/2017 10:32:26 Informational] ========== Discover test finished: 1578 found (0:00:04.6930338) ==========
[22/11/2017 10:32:26 Informational] ------ Run test started ------
[22/11/2017 10:32:27 Informational] NUnit Adapter 3.9.0.0: Test execution started
[22/11/2017 10:32:27 Informational] Running all tests in A:\MoreLINQ\main\MoreLinq.Test\bin\Debug\netcoreapp1.0\MoreLinq.Test.dll
[22/11/2017 10:32:28 Warning] Exception System.NotImplementedException, Exception thrown executing tests in A:\MoreLINQ\main\MoreLinq.Test\bin\Debug\netcoreapp1.0\MoreLinq.Test.dll
[22/11/2017 10:32:28 Warning] GenericInst
[22/11/2017 10:32:28 Warning]    at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type)
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid)
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record)
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Cecil.MethodDefinition.get_DebugInformation()
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.FirstOrDefaultSequencePoint(MethodDefinition testMethod)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName)
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)
[22/11/2017 10:32:28 Informational] NUnit Adapter 3.9.0.0: Test execution complete
[22/11/2017 10:32:28 Warning] No test is available in A:\MoreLINQ\main\MoreLinq.Test\bin\Debug\netcoreapp1.0\MoreLinq.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[22/11/2017 10:32:28 Informational] ========== Run test finished: 0 run (0:00:02.4720149) ==========
```

This was tested on Visual Studio 2017 Enterprise Edition version 15.4.0.

**Comment by atifaziz** [comment]
Seems this got sorted somewhere between Visual Studio 2017 15.4 and 15.7.

**Comment by fsateler** [comment]
Does this mean the test project can go back to being a `dll`?

**Comment by atifaziz** [comment]
It probably can, more so because of #420 than this issue.
