### ISSUE TITLE
Aggregate with FirstAsync & LastAsync modifies collection

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#616]
Using [MoreLINQ 3.2](https://github.com/morelinq/MoreLINQ/releases/tag/v3.2.0), the following:

```c#
var (first, last) =
    Enumerable.Range(1, 10)
              .Aggregate(ds => ds.FirstAsync(),
                         ds => ds.LastAsync(),
                         ValueTuple.Create);
```

throws `InvalidOperationException` with the error message, “Collection was modified; enumeration operation may not execute.”.

The stack trace:

    at System.Collections.Generic.List`1.Enumerator.MoveNext()
    at MoreLinq.Reactive.Subject`1.OnNext(T value) in C:\projects\morelinq\MoreLinq\Reactive\Subject.cs:line 62
    at MoreLinq.Experimental.ExperimentalEnumerable.Aggregate[T,TResult1,TResult2,TResult](IEnumerable`1 source, Func`2 accumulator1, Func`2 accumulator2, Func`3 resultSelector) in C:\projects\morelinq\MoreLinq\Aggregate.g.cs:line 132

indicates a problem with the implementation of `Subject`.

**Comment by atifaziz** [comment]
The race condition occurs below:

https://github.com/morelinq/MoreLINQ/blob/5205ea241d72b079436060d330cd5c2eae7cdcdf/MoreLinq/Reactive/Subject.cs#L60-L61

When the `FirstAsync` or `LastAsync` receive a value, they dispose their subscription _during an iteration_. That disposal modifies the observers collection:

https://github.com/morelinq/MoreLINQ/blob/5205ea241d72b079436060d330cd5c2eae7cdcdf/MoreLinq/Reactive/Subject.cs#L52

The exception then occurs on the next iteration of the loop.
